### ISSUE TITLE
GLMakie interactivity error `InexactError: Int64` 

### ISSUE THREAD

**Issue by jlchan** [j-fu/GridVisualize.jl#6]
When interacting with (e.g., moving, viewing, etc) a GLMakie 3D plot constructed using `scalarplot`, I get repeating stacktraces of `InexactError: Int64` error messages. A MWE from the example is included - nothing is plotted, but the error still appears.
```julia
using ExtendableGrids, GridVisualize

function grid3d(;n=15)
    X=collect(0:1/n:1)
    g=simplexgrid(X,X,X)
end

function func3d(;n=15)
    g=grid3d(n=n)
    g, map((x,y,z)->sinpi(2*x)*sinpi(3.5*y)*sinpi(1.5*z),g)
end    

g,f=func3d(n=25)
scalarplot(g,f; Plotter=Makie)
```
gives `InexactError: Int64(-328.1875)`
```julia
  [7] setindex!(observable::Observable{Tuple{Int64, Int64}}, val::Tuple{Float64, Float64})
    @ Observables ~/.julia/packages/Observables/OFj0u/src/Observables.jl:247
  [8] (::GridVisualize.FlippableLayout.var"#4#6"{Observable{Tuple{Int64, Int64}}})(m::Tuple{Float64, Float64})
    @ GridVisualize.FlippableLayout ~/.julia/packages/GridVisualize/rxNed/src/flippablelayout.jl:147
```
I'm not sure if it's related, but https://github.com/JuliaGeometry/Meshing.jl/issues/42 looks somewhat similar. 

The full stacktrace is included below.
```julia
julia> Error in callback:
InexactError: Int64(-328.1875)
Stacktrace:
  [1] Int64
    @ ./float.jl:723 [inlined]
  [2] convert
    @ ./number.jl:7 [inlined]
  [3] cvt1
    @ ./essentials.jl:322 [inlined]
  [4] ntuple
    @ ./ntuple.jl:49 [inlined]
  [5] convert
    @ ./essentials.jl:323 [inlined]
  [6] setproperty!
    @ ./Base.jl:34 [inlined]
  [7] setindex!(observable::Observable{Tuple{Int64, Int64}}, val::Tuple{Float64, Float64})
    @ Observables ~/.julia/packages/Observables/OFj0u/src/Observables.jl:247
  [8] (::GridVisualize.FlippableLayout.var"#4#6"{Observable{Tuple{Int64, Int64}}})(m::Tuple{Float64, Float64})
    @ GridVisualize.FlippableLayout ~/.julia/packages/GridVisualize/rxNed/src/flippablelayout.jl:147
  [9] #invokelatest#2
    @ ./essentials.jl:708 [inlined]
 [10] invokelatest
    @ ./essentials.jl:706 [inlined]
 [11] (::Makie.PrioCallback)(val::Tuple{Float64, Float64})
    @ Makie ~/.julia/packages/Makie/NL7Xw/src/interaction/PriorityObservable.jl:17
 [12] #invokelatest#2
    @ ./essentials.jl:708 [inlined]
 [13] invokelatest
    @ ./essentials.jl:706 [inlined]
 [14] notify(observable::Makie.PriorityObservable{Tuple{Float64, Float64}})
    @ Makie ~/.julia/packages/Makie/NL7Xw/src/interaction/PriorityObservable.jl:85
 [15] setindex!
    @ ~/.julia/packages/Makie/NL7Xw/src/interaction/PriorityObservable.jl:79 [inlined]
 [16] (::GLMakie.var"#71#72"{Events, GLFW.Window})(#unused#::Nothing)
    @ GLMakie ~/.julia/packages/GLMakie/lcQNS/src/events.jl:6
 [17] #invokelatest#2
    @ ./essentials.jl:708 [inlined]
 [18] invokelatest
    @ ./essentials.jl:706 [inlined]
 [19] notify
    @ ~/.julia/packages/Observables/OFj0u/src/Observables.jl:88 [inlined]
 [20] setindex!(observable::Observable{Nothing}, val::Nothing)
    @ Observables ~/.julia/packages/Observables/OFj0u/src/Observables.jl:248
 [21] fps_renderloop(screen::GLMakie.Screen, framerate::Float64)
    @ GLMakie ~/.julia/packages/GLMakie/lcQNS/src/rendering.jl:22
 [22] renderloop(screen::GLMakie.Screen; framerate::Float64)
    @ GLMakie ~/.julia/packages/GLMakie/lcQNS/src/rendering.jl:48
 [23] renderloop(screen::GLMakie.Screen)
    @ GLMakie ~/.julia/packages/GLMakie/lcQNS/src/rendering.jl:41
 [24] (::GLMakie.var"#50#52"{GLMakie.Screen})()
    @ GLMakie ./task.jl:411
Error in callback:
InexactError: Int64(-180.7890625)
Stacktrace:
  [1] Int64
    @ ./float.jl:723 [inlined]
  [2] convert
    @ ./number.jl:7 [inlined]
  [3] cvt1
    @ ./essentials.jl:322 [inlined]
  [4] ntuple
    @ ./ntuple.jl:49 [inlined]
  [5] convert
    @ ./essentials.jl:323 [inlined]
  [6] setproperty!
    @ ./Base.jl:34 [inlined]
  [7] setindex!(observable::Observable{Tuple{Int64, Int64}}, val::Tuple{Float64, Float64})
    @ Observables ~/.julia/packages/Observables/OFj0u/src/Observables.jl:247
  [8] (::GridVisualize.FlippableLayout.var"#4#6"{Observable{Tuple{Int64, Int64}}})(m::Tuple{Float64, Float64})
    @ GridVisualize.FlippableLayout ~/.julia/packages/GridVisualize/rxNed/src/flippablelayout.jl:147
  [9] #invokelatest#2
    @ ./essentials.jl:708 [inlined]
 [10] invokelatest
    @ ./essentials.jl:706 [inlined]
 [11] (::Makie.PrioCallback)(val::Tuple{Float64, Float64})
    @ Makie ~/.julia/packages/Makie/NL7Xw/src/interaction/PriorityObservable.jl:17
 [12] #invokelatest#2
    @ ./essentials.jl:708 [inlined]
 [13] invokelatest
    @ ./essentials.jl:706 [inlined]
 [14] notify(observable::Makie.PriorityObservable{Tuple{Float64, Float64}})
    @ Makie ~/.julia/packages/Makie/NL7Xw/src/interaction/PriorityObservable.jl:85
 [15] setindex!
    @ ~/.julia/packages/Makie/NL7Xw/src/interaction/PriorityObservable.jl:79 [inlined]
 [16] (::GLMakie.var"#71#72"{Events, GLFW.Window})(#unused#::Nothing)
    @ GLMakie ~/.julia/packages/GLMakie/lcQNS/src/events.jl:6
 [17] #invokelatest#2
    @ ./essentials.jl:708 [inlined]
 [18] invokelatest
    @ ./essentials.jl:706 [inlined]
 [19] notify
    @ ~/.julia/packages/Observables/OFj0u/src/Observables.jl:88 [inlined]
 [20] setindex!(observable::Observable{Nothing}, val::Nothing)
    @ Observables ~/.julia/packages/Observables/OFj0u/src/Observables.jl:248
 [21] fps_renderloop(screen::GLMakie.Screen, framerate::Float64)
    @ GLMakie ~/.julia/packages/GLMakie/lcQNS/src/rendering.jl:22
 [22] renderloop(screen::GLMakie.Screen; framerate::Float64)
    @ GLMakie ~/.julia/packages/GLMakie/lcQNS/src/rendering.jl:48
 [23] renderloop(screen::GLMakie.Screen)
    @ GLMakie ~/.julia/packages/GLMakie/lcQNS/src/rendering.jl:41
 [24] (::GLMakie.var"#50#52"{GLMakie.Screen})()
    @ GLMakie ./task.jl:411
```

**Comment by j-fu** [comment]
Ok found the possible reason. The problem doesn't show up on my system though. 
I pushed a fix to main so you can try this out, will tag later.

With the recent Makie you should pass GLMakie instead of Makie.

**Comment by jlchan** [comment]
Thanks for such a fast response. It didn't fix it, but it helped me find a fix that did. I'll submit a PR for it soon.

**Comment by j-fu** [comment]
Ok was fixed in 4545183ca433b162c834f9ae5e9e35b2c37448c9 , no need for the PR.

**Comment by j-fu** [comment]
Let us see if it works in 0.12.3

**Comment by jlchan** [comment]
I don't think 4545183 fixed it entirely - I checked that branch out and the error remained. https://github.com/j-fu/GridVisualize.jl/pull/7 replaced a similar line in a different file (4545183 changed a line in src/flippablelayout.jl, the PR changed a similar line in src/makie.jl)
